# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{scoped_attr_accessible}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Darcy Laycock", "Mario Visic"]
  s.date = %q{2010-10-15}
  s.description = %q{scoped_attr_accessible is a plugin that makes it easy to scope the `attr_accessible` and `attr_protected`
    methods on any library using ActiveModel's MassAssignmentSecurity module.}
  s.email = %q{team+darcy+mario@thefrontiergroup.com.au}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".bundle/config",
     ".gitignore",
     ".rspec",
     ".rvmrc",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "autotest/discover.rb",
     "lib/scoped_attr_accessible.rb",
     "lib/scoped_attr_accessible/active_model_mixin.rb",
     "lib/scoped_attr_accessible/sanitizer.rb",
     "scoped_attr_accessible.gemspec",
     "spec/scoped_attr_accessible/active_model_mixin_spec.rb",
     "spec/scoped_attr_accessible/sanitizer_spec.rb",
     "spec/scoped_attr_accessible_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/custom_matchers.rb"
  ]
  s.homepage = %q{http://github.com/thefrontiergroup/scoped_attr_accessible}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Scoping for attr_accessible and attr_protected on ActiveModel objects.}
  s.test_files = [
    "spec/scoped_attr_accessible/active_model_mixin_spec.rb",
     "spec/scoped_attr_accessible/sanitizer_spec.rb",
     "spec/scoped_attr_accessible_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/custom_matchers.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activemodel>, ["~> 3.0"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0"])
      s.add_development_dependency(%q<rr>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<ZenTest>, [">= 0"])
    else
      s.add_dependency(%q<activemodel>, ["~> 3.0"])
      s.add_dependency(%q<activesupport>, ["~> 3.0"])
      s.add_dependency(%q<rspec>, ["~> 2.0"])
      s.add_dependency(%q<rr>, [">= 0"])
      s.add_dependency(%q<ruby-debug>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<ZenTest>, [">= 0"])
    end
  else
    s.add_dependency(%q<activemodel>, ["~> 3.0"])
    s.add_dependency(%q<activesupport>, ["~> 3.0"])
    s.add_dependency(%q<rspec>, ["~> 2.0"])
    s.add_dependency(%q<rr>, [">= 0"])
    s.add_dependency(%q<ruby-debug>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<ZenTest>, [">= 0"])
  end
end

